#!/bin/sh

miniconda
conda list

conda create -n pytorch python=3.6.3
source activate pytorch
conda install pytorch torchvision -c pytorch

pip install jupyterlab

# maybe not works
jupyter serverextension enable --py jupyterlab --sys-prefix
