#!/bin/sh

set -ex

# https://pytorch.org/docs/stable/index.html
conda install pytorch torchvision -c pytorch

# https://github.com/jupyterlab/jupyterlab
conda install -c conda-forge jupyterlab

# tensorboard
conda install tensorboard

# altair - # https://altair-viz.github.io/getting_started/installation.html#installation-notebook
conda install -c conda-forge altair vega_datasets jupyterlab
