#!/bin/sh

set -ex

sudo easy_install pip
sudo pip install --upgrade virtualenv
sudo pip install jupyter

mkdir ~/pytorch
virtualenv --system-site-packages  ~/pytorch/pytorch-env

source ~/pytorch/pytorch-env/bin/activate

pip install http://download.pytorch.org/whl/torch-0.2.0.post3-cp27-none-macosx_10_7_x86_64.whl
pip install torchvision

sudo pip install jupyterlab

# maybe not works
jupyter serverextension enable --py jupyterlab --sys-prefix
